import LegalPage from "@/components/LegalPage";

export const metadata = {
  title: "Privacy Policy — OLYR Labs",
  description: "How OLYR Labs collects, uses, protects, and manages personal data.",
};

export default function PrivacyPage() {
  return (
    <LegalPage
      eyebrow="Privacy & data protection"
      title="Privacy Policy"
      updated="3 September 2026"
      intro="This Privacy Policy explains how OLYR Labs handles personal data when you visit olyrlabs.com, contact us, request a quotation, or otherwise communicate with us through our website. We aim to process personal data lawfully, fairly, transparently, and only to the extent reasonably necessary for the stated purpose."
      sections={[
        { title: "Who we are", body: <><p>OLYR Labs is a technology and software development business operating from Sri Lanka. For website enquiries and quotation requests, OLYR Labs is responsible for determining the purposes and means of processing the information you submit.</p><p>Privacy enquiries can be sent to <a className="text-[var(--text)] underline underline-offset-4" href="mailto:hello@olyrlabs.com">hello@olyrlabs.com</a> or by calling +94 78 102 6353.</p></> },
        { title: "Information we collect", body: <><p>When you use our contact form, we may receive your name, email address, company name, and message. When you submit a quotation request, we may receive your name, email address, company, phone number, selected service, project type, project description, budget, timeline, and requirements.</p><p>Our hosting and infrastructure providers may also process limited technical information needed to deliver, secure, and operate the website, such as request metadata, device or browser information, and IP address. We do not intentionally ask website visitors to submit sensitive personal data through these forms.</p></> },
        { title: "How we use personal data", body: <><p>We use submitted information to respond to enquiries, understand project requirements, prepare quotations, communicate about requested services, provide and improve our services, maintain website and system security, prevent abuse or fraud, and comply with applicable legal obligations.</p><p>We do not sell, rent, or trade personal information for advertising purposes.</p></> },
        { title: "Lawful and fair processing", body: <><p>Depending on the circumstances, processing may be necessary to respond to a request or take pre-contractual steps, perform a service agreement, comply with a legal obligation, protect our legitimate interests, or rely on consent where consent is the appropriate basis. We aim to collect information that is adequate, relevant, and proportionate to the purpose for which it is processed.</p><p>This policy is informed by Sri Lanka&apos;s Personal Data Protection Act No. 9 of 2022 and subsequent amendments and guidance. The Act includes obligations concerning purpose, proportionality, accuracy, retention, integrity and confidentiality, transparency, and data-subject rights.</p></> },
        { title: "Service providers and disclosure", body: <><p>We use trusted technology providers to operate the website and deliver requested services. In the current website architecture, quotation information is stored in Supabase and website email delivery is provided through Resend. Contact messages are transmitted through our email service and delivered to our business mailbox.</p><p>We may disclose information to professional advisers, service providers, regulators, law-enforcement authorities, courts, or other parties where disclosure is required or permitted by applicable law, necessary to protect rights or security, or needed to provide a requested service.</p></> },
        { title: "International processing", body: <><p>Some technology providers used to operate a modern web application may process information in countries outside Sri Lanka. Where personal data is transferred across borders, OLYR Labs will seek to apply the safeguards required by applicable Sri Lankan data-protection law and the terms applicable to the relevant service provider.</p><p>We do not represent that every third-party provider stores data exclusively in Sri Lanka. Their own privacy and data-processing terms may also apply to their handling of information.</p></> },
        { title: "Retention", body: <><p>We retain personal data only for as long as reasonably necessary for the purpose for which it was collected, to maintain an ongoing client or enquiry relationship, to meet accounting or legal obligations, resolve disputes, maintain security records, or otherwise comply with applicable law.</p><p>Retention periods can therefore differ depending on the type of information and the reason it was collected. We periodically review information that is no longer needed.</p></> },
        { title: "Your rights", body: <><p>Subject to applicable law and any lawful limitations, you may have rights concerning access to your personal data, withdrawal of consent where processing relies on consent, correction or completion of inaccurate information, erasure in applicable circumstances, and other rights provided by the Sri Lankan PDPA or other law that applies to you.</p><p>Requests can be made by email to <a className="text-[var(--text)] underline underline-offset-4" href="mailto:hello@olyrlabs.com">hello@olyrlabs.com</a>. We may need enough information to verify a request before acting on it.</p></> },
        { title: "Cookies and local preferences", body: <><p>The website currently uses local browser storage to remember your light or dark theme preference. We do not use that preference to identify you.</p><p>If analytics, advertising, embedded services, or other tracking technologies are introduced in the future, this policy and the Cookie Policy will be updated as appropriate.</p></> },
        { title: "Security", body: <><p>We use technical and organisational measures appropriate to the nature of the information we handle, including access controls, secure hosting practices, encrypted transport, restricted server-side secrets, and monitoring or logging where appropriate. No internet transmission or storage system can be guaranteed to be completely secure.</p></> },
        { title: "Children", body: <><p>The website is intended for businesses and general audiences and is not directed at children. We do not knowingly request or intentionally collect children&apos;s personal data through our business enquiry forms.</p></> },
        { title: "Changes", body: <><p>We may update this Privacy Policy when our services, technology, legal obligations, or data practices change. The latest version will be published on this page with a revised update date.</p></> },
      ]}
    />
  );
}
