
import { NextResponse } from "next/server";
import { supabase } from "@/lib/supabase";
import { Resend } from "resend";

const resend = new Resend(process.env.RESEND_API_KEY);

export async function POST(request: Request) {
  try {
    const body = await request.json();

    const {
      name,
      email,
      company,
      phone,
      service,
      project_type,
      description,
      budget,
      timeline,
      requirements,
    } = body;

    // Validate required fields
    if (!name || !email || !service || !description) {
      return NextResponse.json(
        {
          error: "Missing required fields",
        },
        {
          status: 400,
        }
      );
    }

    // Save quote request to Supabase
    const { error: supabaseError } = await supabase
      .from("quote_requests")
      .insert([
        {
          name,
          email,
          company,
          phone,
          service,
          project_type,
          description,
          budget,
          timeline,
          requirements,
          status: "New",
        },
      ]);

    // Handle Supabase error
    if (supabaseError) {
      console.error("Supabase error:", supabaseError);

      return NextResponse.json(
        {
          error: "Database submission failed",
          details: supabaseError.message,
        },
        {
          status: 500,
        }
      );
    }

    // Send notification email to OLYR Labs
    const { error: resendError } = await resend.emails.send({
      from: "OLYR Labs <hello@olyrlabs.com>",
      to: "olyrlabs@gmail.com",
      subject: `New Quote Request - ${service}`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 700px; margin: 0 auto; color: #111111;">

          <h1 style="font-size: 28px; margin-bottom: 8px;">
            New OLYR Labs Quote Request
          </h1>

          <p style="color: #666666; margin-bottom: 30px;">
            A new project quotation request has been submitted through the OLYR Labs website.
          </p>

          <hr style="border: none; border-top: 1px solid #dddddd; margin: 20px 0;" />

          <h2 style="font-size: 20px;">
            Client Information
          </h2>

          <p>
            <strong>Name:</strong>
            ${name}
          </p>

          <p>
            <strong>Email:</strong>
            ${email}
          </p>

          <p>
            <strong>Company:</strong>
            ${company || "Not provided"}
          </p>

          <p>
            <strong>Phone:</strong>
            ${phone || "Not provided"}
          </p>

          <hr style="border: none; border-top: 1px solid #dddddd; margin: 20px 0;" />

          <h2 style="font-size: 20px;">
            Project Information
          </h2>

          <p>
            <strong>Service:</strong>
            ${service}
          </p>

          <p>
            <strong>Project Type:</strong>
            ${project_type || "Not provided"}
          </p>

          <p>
            <strong>Budget:</strong>
            ${budget || "Not provided"}
          </p>

          <p>
            <strong>Timeline:</strong>
            ${timeline || "Not provided"}
          </p>

          <hr style="border: none; border-top: 1px solid #dddddd; margin: 20px 0;" />

          <h2 style="font-size: 20px;">
            Project Description
          </h2>

          <p style="white-space: pre-wrap;">
            ${description}
          </p>

          <h2 style="font-size: 20px; margin-top: 30px;">
            Requirements
          </h2>

          <p style="white-space: pre-wrap;">
            ${requirements || "Not provided"}
          </p>

          <hr style="border: none; border-top: 1px solid #dddddd; margin: 30px 0;" />

          <p style="font-size: 12px; color: #888888;">
            This notification was automatically generated by the OLYR Labs quotation system.
          </p>

        </div>
      `,
    });

    // Handle Resend error
    if (resendError) {
      console.error("Resend error:", resendError);

      return NextResponse.json(
        {
          error: "Quote saved, but notification email failed",
          details: resendError.message,
        },
        {
          status: 500,
        }
      );
    }

    // Successful submission
    return NextResponse.json(
      {
        success: true,
        message: "Quote request submitted successfully",
      },
      {
        status: 200,
      }
    );
  } catch (error) {
    console.error("Quote API error:", error);

    return NextResponse.json(
      {
        error: "Something went wrong",
      },
      {
        status: 500,
      }
    );
  }
}

