"use client";

import { useMemo, useRef, useState } from "react";

type Service = "Website & E-Commerce" | "Custom Software & Automation" | "AI Solutions" | "Cybersecurity Services";
type FormData = { name: string; email: string; company: string; phone: string; service: Service | ""; projectType: string; description: string; requirements: string[]; customRequirements: string; budget: string; timeline: string };

const services: { name: Service; description: string }[] = [
  { name: "Website & E-Commerce", description: "Websites, online stores, redesigns, and digital experiences." },
  { name: "Custom Software & Automation", description: "Business systems, web apps, dashboards, and connected workflows." },
  { name: "AI Solutions", description: "AI assistants, intelligent workflows, data, and custom integrations." },
  { name: "Cybersecurity Services", description: "Security reviews, assessments, testing, and hardening." },
];
const projectTypes: Record<Service, string[]> = {
  "Website & E-Commerce": ["Business / Company Website", "Corporate Website", "Landing Page", "E-Commerce Website", "Online Store", "Website Redesign", "Other"],
  "Custom Software & Automation": ["Business Management System", "Internal Business Platform", "Customer Management System", "Dashboard / Admin Panel", "Workflow Automation", "Custom Web Application", "Custom Software", "Other"],
  "AI Solutions": ["AI Chatbot / Assistant", "AI Business Automation", "AI Data Analysis", "AI Customer Support", "Custom AI System", "AI Integration", "Other"],
  "Cybersecurity Services": ["Website Security Assessment", "Vulnerability Assessment", "Security Review", "Infrastructure Security Review", "Web Application Security", "Domain & Email Security", "Cybersecurity Consultation", "Other"],
};
const requirementOptions: Record<Service, string[]> = {
  "Website & E-Commerce": ["Responsive mobile design", "CMS", "Contact forms", "User accounts", "Admin dashboard", "Payments", "Product catalogue", "Shopping cart", "Orders", "Inventory", "Analytics", "Integrations", "SEO"],
  "Custom Software & Automation": ["Authentication", "Roles & permissions", "Admin dashboard", "Customer management", "Database", "Reports", "Documents", "Notifications", "Email", "Payments", "API integrations", "Automated workflows", "Cloud deployment"],
  "AI Solutions": ["AI chatbot", "AI assistant", "Customer support", "Document analysis", "Data analysis", "AI search", "Content generation", "Workflow automation", "LLM integration", "RAG / knowledge base", "Voice AI", "Image analysis", "Business data integration"],
  "Cybersecurity Services": ["Website assessment", "Vulnerability assessment", "Security headers", "SSL / TLS", "Domain security", "SPF", "DMARC", "DNS security", "Technology analysis", "Infrastructure review", "Web app review", "Risk assessment", "Security report", "Consultation", "Monitoring"],
};
const budgetOptions = ["Under LKR 100,000", "LKR 100,000 – 250,000", "LKR 250,000 – 500,000", "LKR 500,000 – 1,000,000", "LKR 1,000,000+", "Not sure – I need guidance"];
const timelineOptions = ["As soon as possible", "Within 1 month", "1 – 3 months", "3 – 6 months", "6+ months", "Flexible"];
const emptyForm: FormData = { name: "", email: "", company: "", phone: "", service: "", projectType: "", description: "", requirements: [], customRequirements: "", budget: "", timeline: "" };

export default function QuoteForm() {
  const [step, setStep] = useState(1);
  const [formData, setFormData] = useState<FormData>(emptyForm);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [success, setSuccess] = useState(false);
  const assessmentRef = useRef<HTMLDivElement>(null);
  const currentProjectTypes = useMemo(() => formData.service ? projectTypes[formData.service] : [], [formData.service]);
  const currentRequirements = useMemo(() => formData.service ? requirementOptions[formData.service] : [], [formData.service]);
  const updateField = (field: keyof FormData, value: string) => setFormData((p) => ({ ...p, [field]: value }));
  const toggleRequirement = (item: string) => setFormData((p) => ({ ...p, requirements: p.requirements.includes(item) ? p.requirements.filter((x) => x !== item) : [...p.requirements, item] }));
  const validate = () => {
    setError("");
    if (step === 1 && (!formData.name.trim() || !formData.email.trim())) return setError("Please enter your name and email address."), false;
    if (step === 1 && (!formData.email.includes("@") || !formData.email.includes("."))) return setError("Please enter a valid email address."), false;
    if (step === 2 && !formData.service) return setError("Please select a service category."), false;
    if (step === 3 && (!formData.projectType || !formData.description.trim())) return setError("Please choose a project type and describe what you want to build or achieve."), false;
    if (step === 4 && (!formData.budget || !formData.timeline)) return setError("Please select your estimated budget and timeline."), false;
    return true;
  };
  const move = (next: number) => { setError(""); setStep(next); setTimeout(() => assessmentRef.current?.scrollIntoView({ behavior: "smooth", block: "start" }), 40); };
  async function submitForm() {
    if (!validate()) return;
    setLoading(true); setError("");
    try {
      const requirements = [...formData.requirements, ...(formData.customRequirements.trim() ? [`Additional Requirements: ${formData.customRequirements.trim()}`] : [])];
      const response = await fetch("/api/quote", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: formData.name, email: formData.email, company: formData.company, phone: formData.phone, service: formData.service, project_type: formData.projectType, description: formData.description, budget: formData.budget, timeline: formData.timeline, requirements: requirements.join(", ") }) });
      const data = await response.json();
      if (!response.ok) throw new Error(data.error || "Submission failed");
      setSuccess(true); window.scrollTo({ top: 0, behavior: "smooth" });
    } catch (e) { console.error("Quote submission error:", e); setError("Unable to submit your quote request. Please try again."); }
    finally { setLoading(false); }
  }
  if (success) return <div className="relative overflow-hidden rounded-[2.25rem] border border-[var(--border)] bg-[var(--surface)] p-8 shadow-[0_30px_100px_rgba(0,0,0,.14)] sm:p-14"><div className="pointer-events-none absolute -right-24 -top-24 h-72 w-72 rounded-full bg-blue-500/[0.12] blur-[100px]" /><div className="relative text-center"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-blue-500/10 text-2xl text-blue-400">✓</div><p className="mt-7 text-xs font-semibold uppercase tracking-[0.25em] text-[var(--accent)]">Request received</p><h2 className="mt-4 font-[var(--font-space-grotesk)] text-4xl font-semibold tracking-[-0.05em] sm:text-5xl">Thanks. We&apos;ll take it from here.</h2><p className="mx-auto mt-5 max-w-xl text-sm leading-7 text-[var(--muted)]">Your project details are with the OLYR Labs team. We&apos;ll review them and get back to you.</p><button type="button" onClick={() => { setSuccess(false); setStep(1); setFormData(emptyForm); }} className="mt-8 rounded-full border border-[var(--border)] px-6 py-3 text-sm font-semibold transition hover:border-[var(--accent)]">Submit another request</button></div></div>;
  return <section ref={assessmentRef} className="scroll-mt-28"><div className="relative overflow-hidden rounded-[2.25rem] border border-[var(--border)] bg-[var(--surface)] p-6 shadow-[0_30px_100px_rgba(0,0,0,.14)] sm:p-9 lg:p-10"><div className="pointer-events-none absolute -right-28 -top-28 h-80 w-80 rounded-full bg-blue-500/[0.10] blur-[110px]" /><div className="relative"><div className="mb-8 flex items-center gap-2">{Array.from({ length: 5 }).map((_, i) => <span key={i} className={`h-1.5 flex-1 rounded-full transition-all duration-500 ${i < step ? "bg-[var(--accent)]" : "bg-[var(--border)]"}`} />)}</div>{error && <div className="mb-7 rounded-2xl border border-red-400/20 bg-red-400/[0.06] px-4 py-3 text-sm text-red-400">{error}</div>}
  {step === 1 && <Step title="Let&apos;s start with you." description="A few details so we know who we&apos;re speaking with."><div className="grid gap-5 sm:grid-cols-2"><Field label="Name" value={formData.name} onChange={(v) => updateField("name", v)} placeholder="Your name" /><Field label="Email" type="email" value={formData.email} onChange={(v) => updateField("email", v)} placeholder="you@example.com" /></div><div className="mt-5 grid gap-5 sm:grid-cols-2"><Field label="Company" value={formData.company} onChange={(v) => updateField("company", v)} placeholder="Company (optional)" required={false} /><Field label="Phone" value={formData.phone} onChange={(v) => updateField("phone", v)} placeholder="Phone (optional)" required={false} /></div><Actions onNext={() => validate() && move(2)} /></Step>}
  {step === 2 && <Step title="What are we building?" description="Pick the area that best matches what you need."><div className="grid gap-3 sm:grid-cols-2">{services.map((s) => <button key={s.name} type="button" onClick={() => setFormData((p) => ({ ...p, service: s.name, projectType: "", requirements: [] }))} className={`group rounded-2xl border p-5 text-left transition duration-300 ${formData.service === s.name ? "border-[var(--accent)] bg-[var(--accent-soft)]" : "border-[var(--border)] bg-[var(--surface-muted)] hover:-translate-y-0.5 hover:border-[var(--border-strong)]"}`}><span className="mb-8 block h-9 w-9 rounded-xl bg-gradient-to-br from-blue-400/30 to-cyan-300/5 ring-1 ring-blue-300/20" /><span className="font-[var(--font-space-grotesk)] text-lg font-semibold">{s.name}</span><span className="mt-2 block text-sm leading-6 text-[var(--muted)]">{s.description}</span></button>)}</div><Actions onBack={() => move(1)} onNext={() => validate() && move(3)} /></Step>}
  {step === 3 && <Step title="Tell us what you need." description="Choose a project type and give us the useful context."><SelectGrid label="Project type" options={currentProjectTypes} value={formData.projectType} onChange={(v) => updateField("projectType", v)} /><div className="mt-6"><label className="mb-2 block text-sm font-medium">Project details</label><textarea rows={6} value={formData.description} onChange={(e) => updateField("description", e.target.value)} placeholder="What are you trying to build, improve, or solve?" className="w-full resize-none rounded-2xl border border-[var(--border)] bg-[var(--surface-muted)] p-4 text-sm leading-6 text-[var(--text)] outline-none placeholder:text-[var(--subtle)] focus:border-[var(--accent)]" /></div><div className="mt-7"><p className="mb-3 text-sm font-medium">Anything else you need?</p><div className="flex flex-wrap gap-2">{currentRequirements.map((item) => <button key={item} type="button" onClick={() => toggleRequirement(item)} className={`rounded-full border px-3.5 py-2 text-xs transition ${formData.requirements.includes(item) ? "border-[var(--accent)] bg-[var(--accent-soft)] text-[var(--text)]" : "border-[var(--border)] bg-[var(--surface-muted)] text-[var(--muted)] hover:border-[var(--border-strong)]"}`}>{item}</button>)}</div></div><div className="mt-6"><Field label="Additional requirements" value={formData.customRequirements} onChange={(v) => updateField("customRequirements", v)} placeholder="Anything we missed?" required={false} /></div><Actions onBack={() => move(2)} onNext={() => validate() && move(4)} /></Step>}
  {step === 4 && <Step title="Budget and timing." description="This helps us understand the right scope for your project."><SelectGrid label="Estimated budget" options={budgetOptions} value={formData.budget} onChange={(v) => updateField("budget", v)} /><div className="mt-7"><SelectGrid label="Expected timeline" options={timelineOptions} value={formData.timeline} onChange={(v) => updateField("timeline", v)} /></div><Actions onBack={() => move(3)} onNext={() => validate() && move(5)} /></Step>}
  {step === 5 && <Step title="Ready to send." description="Give everything a quick look before we send it."><div className="space-y-3">{[["Contact", `${formData.name} · ${formData.email}`], ["Service", formData.service], ["Project", formData.projectType], ["Budget", formData.budget], ["Timeline", formData.timeline]].map(([label, value]) => <div key={label} className="flex flex-col gap-1 rounded-2xl border border-[var(--border)] bg-[var(--surface-muted)] px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><span className="text-xs uppercase tracking-[0.16em] text-[var(--subtle)]">{label}</span><span className="text-sm font-medium sm:text-right">{value}</span></div>)}</div><div className="mt-4 rounded-2xl border border-[var(--border)] bg-[var(--surface-muted)] p-5"><p className="text-xs uppercase tracking-[0.16em] text-[var(--subtle)]">Project details</p><p className="mt-3 text-sm leading-7 text-[var(--muted)]">{formData.description}</p></div><div className="mt-8 flex flex-col-reverse gap-3 sm:flex-row sm:justify-between"><button type="button" onClick={() => move(4)} className="rounded-full border border-[var(--border)] px-6 py-3 text-sm font-semibold transition hover:border-[var(--accent)]">Back</button><button type="button" disabled={loading} onClick={submitForm} className="rounded-full bg-[var(--text)] px-7 py-3.5 text-sm font-semibold text-[var(--background)] transition hover:-translate-y-0.5 hover:bg-[var(--accent)] hover:text-white disabled:opacity-50">{loading ? "Sending…" : "Send Request →"}</button></div></Step>}
</div></div></section>;
}
function Step({ title, description, children }: { title: string; description: string; children: React.ReactNode }) { return <div><h2 className="font-[var(--font-space-grotesk)] text-3xl font-semibold tracking-[-0.05em] sm:text-4xl">{title}</h2><p className="mt-3 max-w-xl text-sm leading-7 text-[var(--muted)]">{description}</p><div className="mt-8">{children}</div></div>; }
function Actions({ onBack, onNext }: { onBack?: () => void; onNext: () => void }) { return <div className="mt-8 flex flex-col-reverse gap-3 sm:flex-row sm:justify-between">{onBack ? <button type="button" onClick={onBack} className="rounded-full border border-[var(--border)] px-6 py-3 text-sm font-semibold transition hover:border-[var(--accent)]">Back</button> : <span /> }<button type="button" onClick={onNext} className="rounded-full bg-[var(--text)] px-7 py-3.5 text-sm font-semibold text-[var(--background)] transition hover:-translate-y-0.5 hover:bg-[var(--accent)] hover:text-white">Continue →</button></div>; }
function Field({ label, value, onChange, placeholder, type = "text", required = true }: { label: string; value: string; onChange: (v: string) => void; placeholder: string; type?: string; required?: boolean }) { return <div><label className="mb-2 block text-sm font-medium">{label}</label><input type={type} value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder} required={required} className="w-full rounded-2xl border border-[var(--border)] bg-[var(--surface-muted)] px-4 py-3.5 text-sm text-[var(--text)] outline-none placeholder:text-[var(--subtle)] focus:border-[var(--accent)]" /></div>; }
function SelectGrid({ label, options, value, onChange }: { label: string; options: string[]; value: string; onChange: (v: string) => void }) { return <div><p className="mb-3 text-sm font-medium">{label}</p><div className="grid gap-2 sm:grid-cols-2">{options.map((option) => <button key={option} type="button" onClick={() => onChange(option)} className={`rounded-2xl border px-4 py-3.5 text-left text-sm transition ${value === option ? "border-[var(--accent)] bg-[var(--accent-soft)]" : "border-[var(--border)] bg-[var(--surface-muted)] text-[var(--muted)] hover:border-[var(--border-strong)] hover:text-[var(--text)]"}`}>{option}</button>)}</div></div>; }
