import crypto from "crypto";

export type ExposureFinding = { id:string; title:string; severity:"Critical"|"High"|"Medium"; category:"Credentials"|"Endpoints"|"Sensitive Files"; description:string; evidence:string; location:string; discovery:string; confidence:"High"|"Medium"; secretRef?:string };
type Secret = { kind:string; value:string; location:string; source:string; expiresAt:number };
const TTL=15*60*1000, MAX=600000;
function key(){const s=process.env.SECURESCAN_DEVELOPER_SECRET;if(!s||s.length<32)throw Error("SECURESCAN_DEVELOPER_SECRET_MISSING");return crypto.createHash("sha256").update(s).digest();}
export function encryptSecret(x:Omit<Secret,"expiresAt">){const iv=crypto.randomBytes(12),c=crypto.createCipheriv("aes-256-gcm",key(),iv),p=Buffer.from(JSON.stringify({...x,expiresAt:Date.now()+TTL}));const e=Buffer.concat([c.update(p),c.final()]);return `${iv.toString("base64url")}.${c.getAuthTag().toString("base64url")}.${e.toString("base64url")}`;}
export function decryptSecret(t:string):Secret|null{try{const[a,b,c]=t.split("."),d=crypto.createDecipheriv("aes-256-gcm",key(),Buffer.from(a,"base64url"));d.setAuthTag(Buffer.from(b,"base64url"));const x=JSON.parse(Buffer.concat([d.update(Buffer.from(c,"base64url")),d.final()]).toString()) as Secret;return x.expiresAt>Date.now()?x:null;}catch{return null;}}
const paths=["/admin","/admin/login","/login","/signin","/dashboard","/register","/signup","/forgot-password","/reset-password","/api","/api/auth","/api/users","/api/admin","/graphql","/debug","/debug/config","/health","/.env","/.env.local","/.git/config","/robots.txt","/sitemap.xml","/swagger","/swagger.json","/openapi.json","/api-docs","/server-status","/backup.zip"];
function sameOrigin(raw:string,base:URL){try{const u=new URL(raw,base);return u.origin===base.origin&&(u.protocol==="https:"||u.protocol==="http:")?u:null;}catch{return null;}}
async function text(u:URL,s:AbortSignal){const r=await fetch(u,{headers:{"User-Agent":"OLYR-SecureScan-Exposure/1.0"},redirect:"error",signal:s,cache:"no-store"});if(Number(r.headers.get("content-length")||0)>MAX||!r.body)return null;const x=await r.text();return x.length<=MAX?{r,x}:null;}
function urls(html:string,base:URL){const out=new Set<string>(),re=/(?:href|src|action)\s*=\s*["']([^"']+)["']/gi;let m:RegExpExecArray|null;while((m=re.exec(html))&&out.size<80){const u=sameOrigin(m[1],base);if(u)out.add(u.toString());}return [...out];}
function secrets(s:string){const out:{kind:string;value:string}[]=[];const rs=[{kind:"Password",re:/(?:password|passwd|pwd)\s*[:=]\s*["'`]([^"'`\r\n]{6,160})["'`]/gi},{kind:"API key",re:/(?:api[_-]?key|access[_-]?key)\s*[:=]\s*["'`]([A-Za-z0-9_.-]{16,200})["'`]/gi},{kind:"Secret",re:/(?:client[_-]?secret|app[_-]?secret|secret[_-]?key)\s*[:=]\s*["'`]([^"'`\r\n]{12,200})["'`]/gi},{kind:"Bearer token",re:/Bearer\s+([A-Za-z0-9._~+\/=\-]{20,500})/gi}];for(const z of rs){let m:RegExpExecArray|null;while((m=z.re.exec(s))&&out.length<20)out.push({kind:z.kind,value:m[1]});}return out;}
function endpointRefs(s:string,base:URL){const out=new Set<string>(),re=/(?:fetch|axios\.(?:get|post|put|patch|delete))\s*\(\s*["'`]([^"'`]+)["'`]/gi;let m:RegExpExecArray|null;while((m=re.exec(s))&&out.size<60){const u=sameOrigin(m[1],base);if(u)out.add(u.pathname+u.search);}return [...out];}
export async function analyzeExposure(target:URL,signal:AbortSignal){const root=await text(target,signal);if(!root)return{findings:[],discoveredUrls:[],scannedUrls:[]};const discovered=new Set([...urls(root.x,target),...paths.map(p=>new URL(p,target).toString())]),scanned=new Set<string>(),findings:ExposureFinding[]=[];const bodies=[{x:root.x,u:target.toString(),source:"HTML"}];for(const u of urls(root.x,target).filter(x=>/\.m?js(?:\?|$)/i.test(x)).slice(0,6)){const q=await text(new URL(u),signal).catch(()=>null);if(q)bodies.push({x:q.x,u,source:"JavaScript bundle"});}for(const b of bodies){scanned.add(b.u);for(const q of secrets(b.x)){findings.push({id:crypto.randomUUID(),title:`${q.kind} exposed in public content`,severity:q.kind==="Password"?"Critical":"High",category:"Credentials",description:`A ${q.kind.toLowerCase()} pattern was found in unauthenticated public content.`,evidence:`Detected value: ${q.value.slice(0,2)}••••••••${q.value.slice(-2)} (${q.value.length} characters)`,location:b.u,discovery:b.source,confidence:"High",secretRef:encryptSecret({kind:q.kind,value:q.value,location:b.u,source:b.source})});}for(const e of endpointRefs(b.x,target)){discovered.add(new URL(e,target).toString());if(/\/(admin|internal|debug)(?:\/|$)/i.test(e))findings.push({id:crypto.randomUUID(),title:"Sensitive endpoint referenced by client code",severity:"High",category:"Endpoints",description:"Public client code references a potentially sensitive endpoint.",evidence:e,location:b.u,discovery:b.source,confidence:"Medium"});}}for(const raw of [...discovered].filter(x=>!scanned.has(x)).slice(0,80)){const u=new URL(raw),q=await text(u,signal).catch(()=>null);if(!q)continue;scanned.add(raw);if(q.r.status>=200&&q.r.status<400&&/\/(admin|login|signin|dashboard|debug|internal)(?:\/|$)/i.test(u.pathname))findings.push({id:crypto.randomUUID(),title:"Sensitive route is publicly reachable",severity:/\/(admin|debug|internal)(?:\/|$)/i.test(u.pathname)?"High":"Medium",category:"Endpoints",description:"A sensitive-looking route responded successfully without an authentication challenge.",evidence:`${u.pathname} → HTTP ${q.r.status}`,location:u.toString(),discovery:"Endpoint discovery",confidence:"Medium"});if(q.r.status>=200&&q.r.status<400&&/\/(\.env|\.git\/config|backup\.(zip|tar|gz)|server-status)(?:$|\/)/i.test(u.pathname))findings.push({id:crypto.randomUUID(),title:"Sensitive file is publicly reachable",severity:"Critical",category:"Sensitive Files",description:"A potentially sensitive file or diagnostic resource responded to an unauthenticated request.",evidence:`${u.pathname} → HTTP ${q.r.status}`,location:u.toString(),discovery:"Controlled path probe",confidence:"High"});}return{findings,discoveredUrls:[...discovered].slice(0,80),scannedUrls:[...scanned]};}
